
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 13.1 EDK_O.40d
* DO NOT EDIT.
*
* Copyright (c) 1995-2010 Xilinx, Inc.  All rights reserved.

* 
* Description: XilKernel Configuration parameters
*
*******************************************************************/

#ifndef _OS_CONFIG_H
#define _OS_CONFIG_H


#define MB_XILKERNEL 

#define CONFIG_HARDWARE_EXCEPTIONS 

#define CONFIG_PTHREAD_SUPPORT true

#define MAX_PTHREADS 10

#define PTHREAD_STACK_SIZE 1000

#define CONFIG_STATIC_PTHREAD_SUPPORT true

#define N_INIT_SELF_PTHREADS 1

#define CONFIG_TIMER_PIT true

#define SYSTMR_BASEADDR 0x83c20000

#define SYSTMR_INTERVAL 500000

#define SYSTMR_CLK_FREQ 50000000

#define SYSTMR_CLK_FREQ_KHZ 50000

#define CONFIG_INTC true

#define SYSINTC_BASEADDR XPAR_XPS_INTC_1_BASEADDR

#define SYSINTC_DEVICE_ID XPAR_XPS_INTC_1_DEVICE_ID

#define SYSTMR_INTR_ID 1

#define CONFIG_SCHED true

#define SCHED_TYPE SCHED_RR

#define N_PRIO 32

#define CONFIG_RRSCHED true

#define MAX_READYQ 10

#define CONFIG_SEMA true

#define MAX_SEM 10

#define MAX_SEM_WAITQ 10

#define CONFIG_MSGQ true

#define NUM_MSGQS 1

#define MSGQ_CAPACITY 5

#define CONFIG_ENHANCED_MSGQ true

#define USE_MALLOC true

#define CONFIG_TIME true

#define MAX_TMRS 10

#endif
