
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 13.1 EDK_O.40d
* DO NOT EDIT.
*
* Copyright (c) 1995-2010 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xgpio.h"

/*
* The configuration table for devices
*/

XGpio_Config XGpio_ConfigTable[] =
{
	{
		XPAR_BUTTONS_3BIT_DEVICE_ID,
		XPAR_BUTTONS_3BIT_BASEADDR,
		XPAR_BUTTONS_3BIT_INTERRUPT_PRESENT,
		XPAR_BUTTONS_3BIT_IS_DUAL
	},
	{
		XPAR_DIP_SWITCHES_4BIT_DEVICE_ID,
		XPAR_DIP_SWITCHES_4BIT_BASEADDR,
		XPAR_DIP_SWITCHES_4BIT_INTERRUPT_PRESENT,
		XPAR_DIP_SWITCHES_4BIT_IS_DUAL
	},
	{
		XPAR_LEDS_1BIT_DEVICE_ID,
		XPAR_LEDS_1BIT_BASEADDR,
		XPAR_LEDS_1BIT_INTERRUPT_PRESENT,
		XPAR_LEDS_1BIT_IS_DUAL
	},
	{
		XPAR_LEDS_6BIT_DEVICE_ID,
		XPAR_LEDS_6BIT_BASEADDR,
		XPAR_LEDS_6BIT_INTERRUPT_PRESENT,
		XPAR_LEDS_6BIT_IS_DUAL
	}
};


