
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 13.1 EDK_O.40d
* DO NOT EDIT.
*
* Copyright (c) 1995-2010 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xmutex.h"

/*
* The configuration table for devices
*/

XMutex_Config XMutex_ConfigTable[] =
{
	{
		 XPAR_MUTEX_0_IF_1_DEVICE_ID, 
		 XPAR_MUTEX_0_IF_1_BASEADDR, 
		 XPAR_MUTEX_0_IF_1_NUM_MUTEX, 
		 XPAR_MUTEX_0_IF_1_ENABLE_USER, 
	},
};
