
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 13.1 EDK_O.40d
* DO NOT EDIT.
*
* Copyright (c) 1995-2010 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xmbox.h"

/*
 * The configuration table for devices
 */

XMbox_Config XMbox_ConfigTable[] =
{
	{
		 XPAR_MAILBOX_0_IF_1_DEVICE_ID, 
		 XPAR_MAILBOX_0_IF_1_BASEADDR, 
		 XPAR_MAILBOX_0_IF_1_USE_FSL,
		 XPAR_MAILBOX_0_IF_1_SEND_FSL,
		 XPAR_MAILBOX_0_IF_1_RECV_FSL
	},
};
