
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 13.1 EDK_O.40d
* DO NOT EDIT.
*
* Copyright (c) 1995-2010 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xtft.h"

/*
* The configuration table for devices
*/

XTft_Config XTft_ConfigTable[] =
{
	{
		XPAR_XPS_TFT_0_DEVICE_ID,
		XPAR_XPS_TFT_0_SPLB_BASEADDR,
		XPAR_XPS_TFT_0_DEFAULT_TFT_BASE_ADDR,
		XPAR_XPS_TFT_0_DCR_SPLB_SLAVE_IF,
		XPAR_XPS_TFT_0_DCR_BASEADDR
	}
};


